### ISSUE TITLE
"Satoshi amount invalid" on invoice generation

### ISSUE THREAD

**Issue by vitoshi21** [MutinyWallet/mutiny-web#395]
I opened a channel from my node and pushed half the tokens to my mutiny.

When I try to receive (and select any amount that is possible to receive via said channel) I get an error when entering the QR code screen.

See video and logs in attachment.

https://github.com/MutinyWallet/mutiny-web/assets/632900/5800ebd0-75c4-4da7-9158-a9f0bf551200

[mutiny-logs (4).txt](https://github.com/MutinyWallet/mutiny-web/files/12174785/mutiny-logs.4.txt)

**Comment by TonyGiorgio** [comment]
Have you created one for 50k or more to test it out? I see these but I'm unsure why it's failing to get the wrapped invoice from the LSP. Perhaps we're not doing enough logging there or returning the wrong error. 

```
2023-07-24 17:18:02.901 TRACE [lightning_invoice::utils:537] Creating invoice with payment hash aa...
2023-07-24 17:18:02.904 TRACE [lightning_invoice::utils:627] Considering 0 channels for invoice route hints
2023-07-24 17:18:02.942 INFO  [mutiny_core::node:811] SUCCESS: generated invoice: ...
2023-07-24 17:18:03.533 TRACE [mutiny_core::ldkstorage:376] Trace: checking payment key: payment_inbound/a...
```

**Comment by TonyGiorgio** [comment]
Can you provide your node id? We can forward this along to the LSP to see if there's a specific error being returned and for what reason. 

It's in the admin tools settings page, at the very top it will say "nodes" and then you're pubkey.

**Comment by vitoshi21** [comment]
> Can you provide your node id? We can forward this along to the LSP to see if there's a specific error being returned and for what reason. 
> 
> It's in the admin tools settings page, at the very top it will say "nodes" and then you're pubkey. 

036c8e5d825f5fc758e123d4604355f5fe836c0d8100cbeb2b7e21470cca4541b5

**Comment by TonyGiorgio** [comment]
We pushed up an update last friday to log more info if this occurs. If you're willing to try again and see if the error happens, then put the logs here again, that would help.

**Comment by vitoshi21** [comment]
Problem still happened.

Here are the logs as requested.

[mutiny-logs (8).txt](https://github.com/MutinyWallet/mutiny-web/files/12266721/mutiny-logs.8.txt)
